apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
    - image: alpine
      name: alpine
      command: ["/bin/sh"]
      args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
      volumeMounts:
        - name:  data-volume
          mountPath: /opt

  volumes:
    - name: data-volume
      hostPath:
        path: /data
        type: DirectoryOrCreate

    #- name: aws-data-volume
    #  awsElasticBlockStore:
    #    volumeID: <volume-id>
    #    fsType: ext4