apiVersion: admissionregistration.k8s.io/v1
kind: ValidationgWebhookConfiguration
metadata:
  name: "pod-policy.example.com"
webhooks:
- name: "pod-policy.example.com"
  clientConfig:
    service:
      name: "webhook-service"
      namespace: "webhook-namespace"
    caBundle: "CA_BUNDLE"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]