apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create", "get", "update", "delete"]