apiVersion: v1
kind: Pod
metadata:
  name: resource-request
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "1Gi"
        cpu: 1
      limits:
        memory: "2Gi"
        cpu: 2
