apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: webapp
      image: nginx
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /api/healthy
          port: 8080

        # for tcp
        # tcpSocket:
          # port: 3306

        # for exec
        # exec:
          # command:
            # - cat
            # - /app/is_ready
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 8