apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: myapp
      image: busybox
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret
      # env:
      #   - name : DB_PASSWORD
      #     valueFrom:
      #      secretKeyRef:
      #        name: app-secret
      #        key: DB_PASSWORD 